version: '{branch}-{build}'

image: Visual Studio 2017

environment:
  nuget_key:
    secure: EL8Nm3zdLDGQ/nWbP6zZIgCA4k1yJRqmDw4qpK/LYzyl0YebTX1iREmEdUnO0KBS


configuration:
  - Release

branches:
  only:
    - master

skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(version)'
  package_version: '$(version)'
  assembly_version: '$(version)'
  file_version: '$(version)'
  informational_version: '$(version)'

before_build:
  - nuget restore

build:
  project: Ruffles.sln
  verbosity: minimal

after_build:
  - 7z a net35.zip %APPVEYOR_BUILD_FOLDER%\Ruffles\bin\Release\net35\*
  - 7z a net45.zip %APPVEYOR_BUILD_FOLDER%\Ruffles\bin\Release\net45\*
  - 7z a net471.zip %APPVEYOR_BUILD_FOLDER%\Ruffles\bin\Release\net471\*
  - 7z a netcoreapp20.zip %APPVEYOR_BUILD_FOLDER%\Ruffles\bin\Release\netcoreapp2.0\*
  - 7z a netstandard20.zip %APPVEYOR_BUILD_FOLDER%\Ruffles\bin\Release\netstandard2.0\*

cache:
- '%APPDATA%\npm'

install:
- npm install -g semantic-release@15
- npm install -g @semantic-release/github -D
- npm install -g @semantic-release/exec -D
- semantic-release --dry-run

before_deploy:
  - powershell "& "".\package-nuget.ps1"""

artifacts:
- path: '*net*.zip'

deploy_script:
- semantic-release
