version: '{branch}-{build}'

image: Visual Studio 2017

configuration:
  - Release

branches:
  only:
    - master

skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(version)'
  package_version: '$(version)'
  assembly_version: '$(version)'
  file_version: '$(version)'
  informational_version: '$(version)'

before_build:
  - nuget restore

build:
  project: Ruffles.sln
  verbosity: minimal


cache:
- '%APPDATA%\npm'
install:
- npm install -g semantic-release
- semantic-release --dry-run
before_deploy:
  - ps: package-nuget.ps1
artifacts:
- path: 'Ruffles\bin\Release\*\*'
deploy:
  on:
    branch: master
  provider: NuGet
  api_key:
    secure: EL8Nm3zdLDGQ/nWbP6zZIgCA4k1yJRqmDw4qpK/LYzyl0YebTX1iREmEdUnO0KBS
  skip_symbols: false
    artifact: '**\*.nupkg'
deploy_script:
- semantic-release
